-- 20:09 June 8th - Pretty solid - Stuck. - 2nd shit of the day
-- 12:38 June 9th - Nice porridge texture - 1st shit of the day
-- 21:24 June 9th - Defo more solid than the first one - 2nd shit of the day
-- around 16:20 June 10th - Fell out nice - 1st shit of the day
